# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1816d1354c12d5c75f3897ed2b1d14d2ae527894d27e33309fac26d145cce79f811ee4fb06b4dbaa2cc2f3c69edebff8296c9b46e5e58e174be859226dcbd28f

test:
  secret_key_base: f3192ff2376b15ee7c46115c64ae1049afadb07ae246f4601b24b171d9ad2e2124d56999f30141a3d423a89890cb9a9a78e7f71ec44c445cff0d0417adbe6bb4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
